name: CI/CD

on:
  push:
    branches:
      - 'main'

env:
  path: /var/www/armageddon-2023.nikolab131.xyz

jobs:
  build:
    name: 'Build'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Clean
        run : rm -rf ${{env.path}}
      - name: Copy
        run: |
          mkdir -p ${{env.path}}
          cp -r .next/* ${{env.path}}
          cp package.json ${{env.path}}
          cp package-lock.json ${{env.path}}

  deploy:
    needs: build
    name: 'Deploy'
    runs-on: self-hosted

    steps:
      - name: Build
        run: |
          cd ${{env.path}}
          npm ci
      - name: Restart pm2
        run: pm2 restart /var/configs/pm2_ecosystem.config.js --env production
      - name: Save pm2
        run: pm2 save
